title: FAT Forensic Events

show_downloads: false
google_analytics: UA-142154492-3

fatf:
  github: https://github.com/fat-forensics/fat-forensics
  docs: https://fat-forensics.org/

youtube: https://youtu.be/
slack: https://fatforensicsevents.slack.com/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE
  - README.md
  - resources/README.md
  - resources/*/binder
  - resources/*/notebooks
  - resources/*/paper
  - resources/*/slides
  - resources/*/LICENCE
  - resources/*/README.md
  - resources/*/*.sh

include:
  - _quarto

theme: jekyll-theme-hacker

markdown: kramdown
