title: FAT Forensic Events

show_downloads: false
google_analytics: UA-142154492-3

fatf:
  github: https://github.com/fat-forensics/fat-forensics
  docs: https://fat-forensics.org/

youtube: https://youtu.be/
slack: https://fatforensicsevents.slack.com/

exclude:
  - resources
  - binder
  - README.md

theme: jekyll-theme-hacker

markdown: kramdown
